version: '3'

services:
  remote-dev:
    container_name: endstone-remote-dev
    image: endstone/remote-dev
    build: .
    ports:
      - '22:22'
      - '19132:19132/udp'
    volumes:
      - '~/.ssh/:/home/endstone/.ssh/:ro'
